### PR TITLE
Formally update main page with closed CFP

### PR DESCRIPTION
**Pull request by worldwise001**

### CODE REVIEW

**Comment by reedloden** [comment]
Can you update `cfp.md` as well? Something like the combination of https://github.com/BSidesSF/bsidessf.github.io/commit/712450c0fb1bde47dcae86bfe759261a3bd776e2 and https://github.com/BSidesSF/bsidessf.github.io/commit/3cc4ce8006a1dc17750e0cf6bed2192caf998958

**Comment by worldwise001** [comment]
Already on it

**Comment by reedloden** [comment]
What do we need to do with https://bsidessf.org/cfp/villages?

Should we update the nav bar for CFP?

**Review by reedloden — APPROVED** [review]
See my other comments, but it's just additional on top of this.

**Comment by worldwise001** [comment]
Removed the Village link submission, but kept the page for it.

I think I want to rework this whole page at some point, but not tonight.

**Pull request merged**
